#ifndef KernelNotificationShim_h
#define KernelNotificationShim_h

#include <kernel/bitcoinkernel.h>

// Give Swift the header-declared type for every dlsym result. Assigning one of these
// casts to a stale hand-written Swift function signature then fails at compile time.
#define BTCK_DLSYM_SYMBOL(function) \
    static inline __typeof__(&function) btck_dlsym_cast_##function(void* symbol) \
    { \
        return (__typeof__(&function))symbol; \
    }

BTCK_DLSYM_SYMBOL(btck_block_check)
BTCK_DLSYM_SYMBOL(btck_block_copy)
BTCK_DLSYM_SYMBOL(btck_block_count_transactions)
BTCK_DLSYM_SYMBOL(btck_block_create)
BTCK_DLSYM_SYMBOL(btck_block_destroy)
BTCK_DLSYM_SYMBOL(btck_block_get_hash)
BTCK_DLSYM_SYMBOL(btck_block_get_header)
BTCK_DLSYM_SYMBOL(btck_block_get_transaction_at)
BTCK_DLSYM_SYMBOL(btck_block_hash_copy)
BTCK_DLSYM_SYMBOL(btck_block_hash_create)
BTCK_DLSYM_SYMBOL(btck_block_hash_destroy)
BTCK_DLSYM_SYMBOL(btck_block_hash_equals)
BTCK_DLSYM_SYMBOL(btck_block_hash_to_bytes)
BTCK_DLSYM_SYMBOL(btck_block_header_copy)
BTCK_DLSYM_SYMBOL(btck_block_header_create)
BTCK_DLSYM_SYMBOL(btck_block_header_destroy)
BTCK_DLSYM_SYMBOL(btck_block_header_get_bits)
BTCK_DLSYM_SYMBOL(btck_block_header_get_hash)
BTCK_DLSYM_SYMBOL(btck_block_header_get_nonce)
BTCK_DLSYM_SYMBOL(btck_block_header_get_prev_hash)
BTCK_DLSYM_SYMBOL(btck_block_header_get_timestamp)
BTCK_DLSYM_SYMBOL(btck_block_header_get_version)
BTCK_DLSYM_SYMBOL(btck_block_header_to_bytes)
BTCK_DLSYM_SYMBOL(btck_block_read)
BTCK_DLSYM_SYMBOL(btck_block_spent_outputs_copy)
BTCK_DLSYM_SYMBOL(btck_block_spent_outputs_count)
BTCK_DLSYM_SYMBOL(btck_block_spent_outputs_destroy)
BTCK_DLSYM_SYMBOL(btck_block_spent_outputs_get_transaction_spent_outputs_at)
BTCK_DLSYM_SYMBOL(btck_block_spent_outputs_read)
BTCK_DLSYM_SYMBOL(btck_block_to_bytes)
BTCK_DLSYM_SYMBOL(btck_block_tree_entry_equals)
BTCK_DLSYM_SYMBOL(btck_block_tree_entry_get_ancestor)
BTCK_DLSYM_SYMBOL(btck_block_tree_entry_get_block_hash)
BTCK_DLSYM_SYMBOL(btck_block_tree_entry_get_block_header)
BTCK_DLSYM_SYMBOL(btck_block_tree_entry_get_height)
BTCK_DLSYM_SYMBOL(btck_block_tree_entry_get_previous)
BTCK_DLSYM_SYMBOL(btck_block_validation_state_copy)
BTCK_DLSYM_SYMBOL(btck_block_validation_state_create)
BTCK_DLSYM_SYMBOL(btck_block_validation_state_destroy)
BTCK_DLSYM_SYMBOL(btck_block_validation_state_get_block_validation_result)
BTCK_DLSYM_SYMBOL(btck_block_validation_state_get_validation_mode)
BTCK_DLSYM_SYMBOL(btck_chain_contains)
BTCK_DLSYM_SYMBOL(btck_chain_get_by_height)
BTCK_DLSYM_SYMBOL(btck_chain_get_height)
BTCK_DLSYM_SYMBOL(btck_chain_parameters_copy)
BTCK_DLSYM_SYMBOL(btck_chain_parameters_create)
BTCK_DLSYM_SYMBOL(btck_chain_parameters_create_signet)
BTCK_DLSYM_SYMBOL(btck_chain_parameters_destroy)
BTCK_DLSYM_SYMBOL(btck_chain_parameters_get_consensus_params)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_create)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_destroy)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_get_active_chain)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_get_best_entry)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_get_block_tree_entry_by_hash)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_import_blocks)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_options_create)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_options_destroy)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_options_set_wipe_dbs)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_options_set_worker_threads_num)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_options_update_block_tree_db_in_memory)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_options_update_chainstate_db_in_memory)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_process_block)
BTCK_DLSYM_SYMBOL(btck_chainstate_manager_process_block_header)
BTCK_DLSYM_SYMBOL(btck_coin_confirmation_height)
BTCK_DLSYM_SYMBOL(btck_coin_copy)
BTCK_DLSYM_SYMBOL(btck_coin_destroy)
BTCK_DLSYM_SYMBOL(btck_coin_get_output)
BTCK_DLSYM_SYMBOL(btck_coin_is_coinbase)
BTCK_DLSYM_SYMBOL(btck_context_copy)
BTCK_DLSYM_SYMBOL(btck_context_create)
BTCK_DLSYM_SYMBOL(btck_context_destroy)
BTCK_DLSYM_SYMBOL(btck_context_interrupt)
BTCK_DLSYM_SYMBOL(btck_context_options_create)
BTCK_DLSYM_SYMBOL(btck_context_options_destroy)
BTCK_DLSYM_SYMBOL(btck_context_options_set_chainparams)
BTCK_DLSYM_SYMBOL(btck_logging_connection_create)
BTCK_DLSYM_SYMBOL(btck_logging_connection_destroy)
BTCK_DLSYM_SYMBOL(btck_logging_disable_category)
BTCK_DLSYM_SYMBOL(btck_logging_enable_category)
BTCK_DLSYM_SYMBOL(btck_logging_set_level_category)
BTCK_DLSYM_SYMBOL(btck_precomputed_transaction_data_copy)
BTCK_DLSYM_SYMBOL(btck_precomputed_transaction_data_create)
BTCK_DLSYM_SYMBOL(btck_precomputed_transaction_data_destroy)
BTCK_DLSYM_SYMBOL(btck_script_pubkey_copy)
BTCK_DLSYM_SYMBOL(btck_script_pubkey_create)
BTCK_DLSYM_SYMBOL(btck_script_pubkey_destroy)
BTCK_DLSYM_SYMBOL(btck_script_pubkey_to_bytes)
BTCK_DLSYM_SYMBOL(btck_script_pubkey_verify)
BTCK_DLSYM_SYMBOL(btck_transaction_check)
BTCK_DLSYM_SYMBOL(btck_transaction_copy)
BTCK_DLSYM_SYMBOL(btck_transaction_count_inputs)
BTCK_DLSYM_SYMBOL(btck_transaction_count_outputs)
BTCK_DLSYM_SYMBOL(btck_transaction_create)
BTCK_DLSYM_SYMBOL(btck_transaction_destroy)
BTCK_DLSYM_SYMBOL(btck_transaction_get_input_at)
BTCK_DLSYM_SYMBOL(btck_transaction_get_locktime)
BTCK_DLSYM_SYMBOL(btck_transaction_get_output_at)
BTCK_DLSYM_SYMBOL(btck_transaction_get_txid)
BTCK_DLSYM_SYMBOL(btck_transaction_input_copy)
BTCK_DLSYM_SYMBOL(btck_transaction_input_destroy)
BTCK_DLSYM_SYMBOL(btck_transaction_input_get_out_point)
BTCK_DLSYM_SYMBOL(btck_transaction_input_get_script_sig)
BTCK_DLSYM_SYMBOL(btck_transaction_input_get_sequence)
BTCK_DLSYM_SYMBOL(btck_transaction_input_get_witness_stack)
BTCK_DLSYM_SYMBOL(btck_transaction_out_point_copy)
BTCK_DLSYM_SYMBOL(btck_transaction_out_point_destroy)
BTCK_DLSYM_SYMBOL(btck_transaction_out_point_get_index)
BTCK_DLSYM_SYMBOL(btck_transaction_out_point_get_txid)
BTCK_DLSYM_SYMBOL(btck_transaction_output_copy)
BTCK_DLSYM_SYMBOL(btck_transaction_output_create)
BTCK_DLSYM_SYMBOL(btck_transaction_output_destroy)
BTCK_DLSYM_SYMBOL(btck_transaction_output_get_amount)
BTCK_DLSYM_SYMBOL(btck_transaction_output_get_script_pubkey)
BTCK_DLSYM_SYMBOL(btck_transaction_spent_outputs_copy)
BTCK_DLSYM_SYMBOL(btck_transaction_spent_outputs_count)
BTCK_DLSYM_SYMBOL(btck_transaction_spent_outputs_destroy)
BTCK_DLSYM_SYMBOL(btck_transaction_spent_outputs_get_coin_at)
BTCK_DLSYM_SYMBOL(btck_transaction_to_bytes)
BTCK_DLSYM_SYMBOL(btck_tx_validation_state_create)
BTCK_DLSYM_SYMBOL(btck_tx_validation_state_destroy)
BTCK_DLSYM_SYMBOL(btck_tx_validation_state_get_tx_validation_result)
BTCK_DLSYM_SYMBOL(btck_tx_validation_state_get_validation_mode)
BTCK_DLSYM_SYMBOL(btck_txid_copy)
BTCK_DLSYM_SYMBOL(btck_txid_destroy)
BTCK_DLSYM_SYMBOL(btck_txid_equals)
BTCK_DLSYM_SYMBOL(btck_txid_to_bytes)
BTCK_DLSYM_SYMBOL(btck_witness_stack_copy)
BTCK_DLSYM_SYMBOL(btck_witness_stack_count_items)
BTCK_DLSYM_SYMBOL(btck_witness_stack_destroy)
BTCK_DLSYM_SYMBOL(btck_witness_stack_get_item_at)

#undef BTCK_DLSYM_SYMBOL

#define BTCK_SWIFT_CONSTANT(constant) \
    static inline __typeof__(constant) btck_swift_##constant(void) \
    { \
        return constant; \
    }

BTCK_SWIFT_CONSTANT(btck_BlockCheckFlags_ALL)
BTCK_SWIFT_CONSTANT(btck_ChainType_SIGNET)
BTCK_SWIFT_CONSTANT(btck_LogCategory_ALL)
BTCK_SWIFT_CONSTANT(btck_LogLevel_DEBUG)
BTCK_SWIFT_CONSTANT(btck_LogLevel_INFO)
BTCK_SWIFT_CONSTANT(btck_ScriptVerificationFlags_ALL)
BTCK_SWIFT_CONSTANT(btck_ScriptVerifyStatus_OK)
BTCK_SWIFT_CONSTANT(btck_SynchronizationState_INIT_DOWNLOAD)
BTCK_SWIFT_CONSTANT(btck_SynchronizationState_INIT_REINDEX)
BTCK_SWIFT_CONSTANT(btck_SynchronizationState_POST_INIT)
BTCK_SWIFT_CONSTANT(btck_TxValidationResult_UNSET)
BTCK_SWIFT_CONSTANT(btck_ValidationMode_INTERNAL_ERROR)
BTCK_SWIFT_CONSTANT(btck_ValidationMode_INVALID)
BTCK_SWIFT_CONSTANT(btck_ValidationMode_VALID)
BTCK_SWIFT_CONSTANT(btck_Warning_LARGE_WORK_INVALID_CHAIN)
BTCK_SWIFT_CONSTANT(btck_Warning_UNKNOWN_NEW_RULES_ACTIVATED)

#undef BTCK_SWIFT_CONSTANT

void btck_call_context_options_set_notifications(
    void* function,
    btck_ContextOptions* context_options,
    btck_NotificationInterfaceCallbacks notifications
);

void btck_call_context_options_set_validation_interface(
    void* function,
    btck_ContextOptions* context_options,
    btck_ValidationInterfaceCallbacks validation_interface
);

void btck_call_logging_set_options(
    void* function,
    btck_LoggingOptions options
);

void btck_call_logging_disable(
    void* function
);

#endif
